#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/out}"
DIST_DIR="${DIST_DIR:-}"
KERNEL_IMAGE="${KERNEL_IMAGE:-}"
AK3_REPO="${AK3_REPO:-https://github.com/osm0sis/AnyKernel3.git}"
AK3_BRANCH="${AK3_BRANCH:-master}"
DEVICE_CODENAME="${DEVICE_CODENAME:-sm8850}"
DEVICE_NAME="${DEVICE_NAME:-Xiaomi SM8850}"
KERNEL_NAME="${KERNEL_NAME:-KokubanKernel-SukiSU-Ultra}"
ZIP_NAME="${ZIP_NAME:-}"
WORK_DIR="${WORK_DIR:-$ROOT_DIR/out/anykernel3}"
ARTIFACT_DIR="${ARTIFACT_DIR:-$ROOT_DIR/out/anykernel3-dist}"
KEEP_WORKDIR="${KEEP_WORKDIR:-0}"

usage() {
	cat <<EOF
Usage:
  KERNEL_IMAGE=/path/to/Image.lz4 $0
  DIST_DIR=/path/to/dist $0

Environment:
  KERNEL_IMAGE     Explicit kernel image path. Preferred when set.
  DIST_DIR         Directory containing Image, Image.gz, or Image.lz4.
  OUT_DIR          Fallback search root. Default: $ROOT_DIR/out
  AK3_REPO         AnyKernel3 git repo. Default: $AK3_REPO
  AK3_BRANCH       AnyKernel3 branch/ref. Default: $AK3_BRANCH
  DEVICE_CODENAME  Device codename label. Default: $DEVICE_CODENAME
  DEVICE_NAME      Human readable device name. Default: $DEVICE_NAME
  KERNEL_NAME      Zip/kernel display name. Default: $KERNEL_NAME
  ZIP_NAME         Output zip filename. Default: auto generated.
  WORK_DIR         Temporary AnyKernel3 workspace. Default: $WORK_DIR
  ARTIFACT_DIR     Output directory. Default: $ARTIFACT_DIR
  KEEP_WORKDIR     Set to 1 to keep generated AnyKernel3 workspace.
EOF
}

log() {
	printf '[AnyKernel3] %s\n' "$*"
}

die() {
	printf '[AnyKernel3] ERROR: %s\n' "$*" >&2
	exit 1
}

require_cmd() {
	command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

find_kernel_image() {
	local candidates=()
	local dir

	if [[ -n "$KERNEL_IMAGE" ]]; then
		[[ -f "$KERNEL_IMAGE" ]] || die "KERNEL_IMAGE does not exist: $KERNEL_IMAGE"
		printf '%s\n' "$KERNEL_IMAGE"
		return
	fi

	if [[ -n "$DIST_DIR" ]]; then
		[[ -d "$DIST_DIR" ]] || die "DIST_DIR does not exist: $DIST_DIR"
		candidates+=(
			"$DIST_DIR/Image.lz4"
			"$DIST_DIR/Image.gz"
			"$DIST_DIR/Image"
			"$DIST_DIR/arch/arm64/boot/Image.lz4"
			"$DIST_DIR/arch/arm64/boot/Image.gz"
			"$DIST_DIR/arch/arm64/boot/Image"
		)
	fi

	candidates+=(
		"$OUT_DIR/dist/Image.lz4"
		"$OUT_DIR/dist/Image.gz"
		"$OUT_DIR/dist/Image"
		"$OUT_DIR/arch/arm64/boot/Image.lz4"
		"$OUT_DIR/arch/arm64/boot/Image.gz"
		"$OUT_DIR/arch/arm64/boot/Image"
		"$ROOT_DIR/bazel-bin/Image.lz4"
		"$ROOT_DIR/bazel-bin/Image.gz"
		"$ROOT_DIR/bazel-bin/Image"
	)

	for image in "${candidates[@]}"; do
		if [[ -f "$image" ]]; then
			printf '%s\n' "$image"
			return
		fi
	done

	for dir in "$ROOT_DIR/bazel-bin" "$OUT_DIR" "$ROOT_DIR/out"; do
		[[ -d "$dir" ]] || continue
		local found
		found="$(find "$dir" -type f \( -name Image.lz4 -o -name Image.gz -o -name Image \) \
			-not -path '*/intermediates/*' -not -path '*/.git/*' | sort | head -n 1 || true)"
		if [[ -n "$found" ]]; then
			printf '%s\n' "$found"
			return
		fi
	done

	die "kernel image not found. Set KERNEL_IMAGE=/path/to/Image.lz4 or DIST_DIR=/path/to/dist."
}

write_anykernel_config() {
	local ak3_dir="$1"
	local image_file="$2"
	local build_id="$3"

	cat >"$ak3_dir/anykernel.sh" <<EOF
# AnyKernel3 Ramdisk Mod Script
# Generated by scripts/package_anykernel3.sh

properties() { '
kernel.string=$KERNEL_NAME $build_id for $DEVICE_NAME
do.devicecheck=0
do.modules=0
do.systemless=1
do.cleanup=1
do.cleanuponabort=0
device.name1=$DEVICE_CODENAME
device.name2=$DEVICE_NAME
supported.versions=
supported.patchlevels=
'; }

block=/dev/block/bootdevice/by-name/boot;
is_slot_device=auto;
ramdisk_compression=auto;
patch_vbmeta_flag=auto;

. tools/ak3-core.sh;

dump_boot;
write_boot;
EOF

	cp "$image_file" "$ak3_dir/$(basename "$image_file")"
}

make_zip() {
	local ak3_dir="$1"
	local zip_path="$2"

	(
		cd "$ak3_dir"
		zip -r9 "$zip_path" . \
			-x '.git/*' \
			-x 'README.md' \
			-x '*placeholder' \
			-x '*.zip'
	)
}

main() {
	if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
	usage
	exit 0
	fi

	require_cmd git
	require_cmd zip

	local image_file
	image_file="$(find_kernel_image)"
	image_file="$(cd "$(dirname "$image_file")" && pwd)/$(basename "$image_file")"

	local short_sha
	short_sha="$(git -C "$ROOT_DIR" rev-parse --short=8 HEAD 2>/dev/null || printf unknown)"
	local date_tag
	date_tag="$(date -u +%Y%m%d-%H%M)"
	local build_id="${short_sha}-${date_tag}"

	if [[ -z "$ZIP_NAME" ]]; then
		ZIP_NAME="${KERNEL_NAME}-${DEVICE_CODENAME}-${build_id}.zip"
	fi

	mkdir -p "$ARTIFACT_DIR"
	rm -rf "$WORK_DIR"

	log "kernel image: $image_file"
	log "cloning AnyKernel3: $AK3_REPO ($AK3_BRANCH)"
	git clone --depth 1 --branch "$AK3_BRANCH" "$AK3_REPO" "$WORK_DIR"
	rm -rf "$WORK_DIR/.git" "$WORK_DIR/.github"

	write_anykernel_config "$WORK_DIR" "$image_file" "$build_id"

	local zip_path="$ARTIFACT_DIR/$ZIP_NAME"
	rm -f "$zip_path"
	make_zip "$WORK_DIR" "$zip_path"

	log "created: $zip_path"
	if [[ "$KEEP_WORKDIR" != "1" ]]; then
		rm -rf "$WORK_DIR"
	fi
}

main "$@"
